services:
  db:
    container_name: imei_checker_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
    ports:
      - "${EXTERNAL_PORT_DB}:${INNER_PORT_DB}"
    volumes:
      - shop_bot_db:/var/lib/postgresql/data

volumes:
  shop_bot_db: