"""migrration white_user

Revision ID: 626b087878be
Revises: 
Create Date: 2025-01-31 19:03:02.392149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626b087878be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('white_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id чата', sa.Integer(), nullable=False),
    sa.Column('никнейм', sa.String(length=200), nullable=True),
    sa.Column('имя', sa.String(length=200), nullable=False),
    sa.Column('фамилия', sa.String(length=200), nullable=True),
    sa.Column('дата создания', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('дата обновления', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_user')
    # ### end Alembic commands ###
